export const totQuestions = [
  "Coca-Cola atau Sprite?",
  "Kopi atau non kopi?",
  "Coklat atau keju?",
  "Es krim atau yogurt?",
  "Nasi goreng atau mie goreng?",
  "Ayam goreng atau ayam bakar?",
  "Sate ayam atau sate kambing?",
  "Makan pedas atau makan manis?",
  "Roti tawar atau roti isi?",
  "Burger atau pizza?",
  "Kentang goreng atau onion ring?",
  "Teh manis atau lemon tea?",
  "Air putih dingin atau hangat?",
  "Keripik atau kacang?",
  "Sarapan atau skip sarapan?",
  "Nasi padang atau nasi uduk?",
  "Martabak manis atau martabak telur?",
  "Bakso atau soto?",
  "Indomie rebus atau goreng?",
  "Donat atau kue bolu?",
  "Ngemil atau makan berat?",
  "Beli jajan atau masak sendiri?",
  "Kue kering atau kue basah?",
  "Makan pakai tangan atau sendok garpu?",
  "Duduk lesehan atau di kursi?",
  "Tidur siang atau begadang?",
  "Nonton film atau dengerin musik?",
  "Ngopi di kafe atau di rumah?",
  "Main game atau baca buku?",
  "Nonton bioskop atau Netflix-an?",
  "Selfie atau foto pemandangan?",
  "Pakai baju hitam atau putih?",
  "Sneakers atau sandal?",
  "Celana jeans atau celana bahan?",
  "Dompet atau card holder?",
  "Tas ransel atau tas selempang?",
  "Motor atau mobil?",
  "Naik kendaraan umum atau jalan kaki?",
  "Belanja online atau belanja langsung?",
  "Shopee atau Tokopedia?",
  "Instagram atau TikTok?",
  "Chat atau telepon?",
  "WhatsApp atau Telegram?",
  "iPhone atau Android?",
  "Laptop atau tablet?",
  "Google atau YouTube?",
  "Netflix atau Disney+?",
  "Drama Korea atau anime?",
  "Spotify atau YouTube Music?",
  "Bangun pagi atau tidur larut?",
  "Hari libur di rumah atau jalan-jalan?",
  "Liburan ke pantai atau gunung?",
  "Staycation atau backpacker-an?",
  "Main ke mall atau ke taman?",
  "Pakai parfum manis atau segar?",
  "Nonton horor atau komedi?",
  "Tidur pakai bantal banyak atau satu aja?",
  "Minum pakai sedotan atau langsung dari gelas?",
  "Makan siang sendiri atau rame-rame?",
  "Belajar pagi atau malam?",
  "Ujan deras atau cuaca panas?",
];

export const totQuestions2 = [
  "Didiemin atau dimarahin langsung?",
  "Ditinggal pas sayang-sayangnya atau ditolak sebelum mulai?",
  "Menyendiri seminggu atau ketemu orang terus seminggu?",
  "Cerita ke teman atau pendam sendiri?",
  "Minta maaf duluan atau tunggu dimaafin?",
  "Dikhianati teman atau pasangan?",
  "Kejujuran yang menyakitkan atau kebohongan yang bikin tenang?",
  "Bertahan demi cinta atau lepaskan demi logika?",
  "Dikenal tapi disalahpahami atau tidak dikenal tapi damai?",
  "Diam tapi menyesal atau jujur tapi berisiko?",
  "Balikan sama mantan atau mulai dari nol dengan orang baru?",
  "Pasangan super sibuk tapi sayang atau punya waktu tapi cuek?",
  "Jadi pendengar atau jadi pembicara?",
  "Pacaran lama tapi nggak pasti atau baru kenal tapi serius?",
  "Disukai banyak orang atau dicintai satu orang saja?",
  "Sukses di usia muda atau bahagia di usia tua?",
  "Punya banyak teman tapi nggak dekat atau satu teman tapi akrab banget?",
  "Nunggu lama tapi pasti atau cepat tapi belum tentu cocok?",
  "Tinggal dekat keluarga atau tinggal sendiri di kota lain?",
  "Lebih baik nggak usah kenal atau pernah kenal tapi sakit?",
  "Dipaksa berubah atau ditinggal tanpa alasan?",
  "Bersahabat dengan mantan atau blokir selamanya?",
  "Simpan perasaan atau ungkapkan meski ditolak?",
  "Memaafkan tanpa minta maaf atau menunggu minta maaf?",
  "Chat tiap hari tapi flat atau jarang tapi selalu seru?",
  "Punya pasangan yang overthinking atau pasangan yang cuek?",
  "Gagal tapi mencoba atau tidak pernah mencoba sama sekali?",
  "Jujur tapi menyakitkan atau bohong demi kebaikan?",
  "Cinta lama bersemi kembali atau cinta baru penuh misteri?",
  "Orang tua ketat tapi perhatian atau bebas tapi cuek?",
  "Dituduh tanpa bukti atau dicuekin tanpa alasan?",
  "Tahu semuanya tapi sakit atau nggak tahu apa-apa tapi bahagia?",
  "Mantan balikan sama temanmu atau kamu yang balikan diam-diam?",
  "Pasangan sering ngambek atau kamu yang harus selalu ngalah?",
  "Tinggal bareng pasangan sebelum nikah atau setelah nikah aja?",
  "Ngobrol face to face atau via chat aja?",
  "Pasangan aktif di medsos atau nggak punya sosmed sama sekali?",
  "Putus baik-baik atau ghosting aja?",
  "Teman toxic tapi seru atau teman biasa tapi sehat?",
  "Cemburu diam-diam atau langsung ngomong?",
];

export const totQuestions3 = [
  "Punya pasangan yang cuek tapi setia atau perhatian tapi manipulatif?",
  "Maafin selingkuh sekali atau putus tanpa penjelasan?",
  "Menikah tanpa cinta atau cinta tanpa bisa menikah?",
  "Diselingkuhi tapi nggak tahu atau tahu tapi nggak bisa ninggalin?",
  "Menikah muda tapi tidak siap atau tua tapi kesepian?",
  "Dibandingkan terus sama mantan atau kamu yang terus membandingkan?",
  "Cinta sepihak bertahun-tahun atau hubungan tanpa rasa cinta?",
  "Nggak disukai orang tua pasangan atau kamu nggak suka orang tuanya?",
  "Dipaksa menikah atau nggak pernah dinikahi?",
  "Hubungan rahasia atau hubungan yang diaibkan?",
  "Punya anak tanpa pasangan atau pasangan tapi nggak bisa punya anak?",
  "Diprioritaskan tapi dikekang atau diabaikan tapi bebas?",
  "Menikah karena cinta atau karena desakan keluarga?",
  "Pasangan selingkuh tapi jujur atau setia tapi menyimpan rahasia besar?",
  "LDR selamanya atau bareng tapi selalu bertengkar?",
  "Dipukul tapi minta maaf atau diteror secara emosional?",
  "Ditinggal selingkuh atau ditinggal meninggal?",
  "Nggak pernah diseriusin atau cuma dijadiin pelarian?",
  "Jadi orang ketiga atau diselingkuhi?",
  "Cinta beda agama atau beda prinsip hidup?",
  "Pasangan manipulatif tapi kamu cinta banget atau hubungan hambar tapi sehat?",
  "Disuruh pilih: cinta atau keluarga?",
  "Terjebak dalam pernikahan tanpa cinta atau hidup sendiri selamanya?",
  "Diputusin saat kamu sakit atau saat ulang tahun?",
  "Menikah demi anak atau demi status sosial?",
  "Selalu minta maaf meskipun nggak salah atau selalu merasa benar?",
  "Mengetahui rahasia kelam pasangan atau disimpan selamanya?",
  "Menikah tapi gak bahagia atau bahagia tapi gak bisa menikah?",
  "Pasangan perfect tapi gak cinta atau cinta banget tapi toxic?",
  "Hidup dalam kebohongan indah atau kebenaran yang menyakitkan?",
  "Nggak pernah punya pasangan atau terus disakiti dalam hubungan?",
  "Pasangan posesif banget atau kamu nggak pernah dicariin?",
  "Diselingkuhi dengan orang terdekat atau orang asing?",
  "Dihargai tapi gak dicintai atau dicintai tapi gak dihargai?",
  "Pasangan kamu berubah agama atau orientasi?",
  "Pasangan gak punya ambisi atau terlalu ambisius sampai lupa kamu?",
  "Kehilangan pasangan karena orang tua atau karena pilihan sendiri?",
  "Nyesel menikah atau nyesel gak nikah?",
  "Hubunganmu diatur orang tua atau pasanganmu sendiri?",
  "Menikah dengan mantan atau sahabat?",
];

export const dtpQuestions = [
  "Apa yang pertama kali bikin kamu tertarik padaku?",
  "Bagaimana kamu tahu bahwa kamu jatuh cinta padaku?",
  "Apa ketakutan terbesarmu dalam hubungan ini?",
  "Hal apa dalam diriku yang paling kamu syukuri?",
  "Apa yang menurutmu paling sulit dalam menjaga hubungan?",
  "Bagaimana kamu ingin kita menyelesaikan konflik di masa depan?",
  "Pernahkah kamu merasa tidak cukup baik dalam hubungan ini?",
  "Bagaimana cara terbaik aku menunjukkan cinta kepadamu?",
  "Apa harapanmu untuk hubungan kita lima tahun ke depan?",
  "Bagian mana dari masa lalumu yang masih membentuk dirimu saat ini?",
  "Bagaimana kamu mendefinisikan komitmen dalam hubungan?",
  "Apa yang kamu takutkan jika kita terlalu dekat?",
  "Apa yang membuatmu merasa benar-benar aman dalam hubungan ini?",
  "Apa momen paling berarti yang pernah kita lewati bersama?",
  "Bagaimana caramu memproses rasa cemburu dalam hubungan?",
  "Apa yang membuatmu merasa didengar dan dimengerti olehku?",
  "Hal apa yang kamu takutkan aku tidak akan mengerti tentangmu?",
  "Apa satu hal yang belum pernah kamu ceritakan padaku, tapi ingin kamu bagi suatu hari nanti?",
  "Apa yang kamu harapkan bisa lebih sering kita lakukan bersama?",
  "Apa arti 'rumah' dalam konteks hubungan bagi kamu?",
  "Apa kekhawatiranmu tentang masa depan kita?",
  "Apa bentuk kasih sayang yang paling membuatmu merasa dicintai?",
  "Kapan kamu merasa paling rentan dalam hubungan ini?",
  "Jika kita sedang menghadapi masa sulit, apa yang kamu ingin aku lakukan?",
  "Apa yang paling kamu butuhkan dariku saat kamu merasa sedih?",
  "Apakah kamu merasa kita sudah jujur sepenuhnya satu sama lain?",
  "Apa yang menurutmu bisa kita perbaiki dalam cara kita berkomunikasi?",
  "Apa yang kamu pelajari tentang cinta dari hubungan kita?",
  "Apa satu hal tentang diriku yang kamu takut akan berubah seiring waktu?",
  "Apa impian terbesar kamu yang ingin aku dukung sepenuhnya?",
  "Apa rasa sakit terbesar yang masih kamu bawa, dan bagaimana aku bisa membantumu pulih?",
  "Apakah ada bagian dari dirimu yang belum bisa kamu tunjukkan ke aku sepenuhnya? Kenapa?",
  "Kapan terakhir kamu merasa benar-benar terhubung denganku?",
  "Apa artinya setia menurutmu?",
  "Apakah kamu merasa dicintai apa adanya olehku?",
  "Bagaimana kamu membayangkan hubungan ideal kita ke depannya?",
  "Apa ketakutan terbesar kamu jika hubungan ini gagal?",
  "Apa satu hal yang selalu ingin kamu lakukan bersamaku tapi belum sempat?",
  "Apa peran pasangan dalam proses penyembuhan luka masa lalu menurutmu?",
  "Apa momen kecil dariku yang diam-diam kamu ingat sampai sekarang?",
  "Bagaimana aku bisa menjadi pasangan yang lebih baik bagimu?",
  "Apa hal paling menyakitkan yang pernah kamu alami dalam hubungan sebelum ini?",
  "Apa yang menurutmu paling bisa menghancurkan kepercayaan dalam hubungan?",
  "Apa yang membuatmu yakin bahwa aku adalah orang yang tepat untukmu?",
  "Apakah kamu merasa bebas menjadi diri sendiri saat bersamaku?",
  "Bagaimana cara kamu mengekspresikan cinta ketika kata-kata tidak cukup?",
  "Apa perasaan yang paling sulit kamu ungkapkan kepadaku?",
  "Apa yang membuatmu merasa dihargai dalam hubungan ini?",
  "Apakah kamu pernah merasa sendirian walaupun kita sedang bersama?",
  "Bagaimana kamu ingin aku mencintaimu saat kamu sedang tidak baik-baik saja?",
];

export const whatIfQuestions = [
  "Apa yang akan kamu lakukan jika kamu bisa menghentikan waktu?",
  "Bagaimana jika kamu bisa membaca pikiran orang lain?",
  "Kalau kamu jadi presiden sehari, apa yang kamu lakukan?",
  "Bagaimana jika kamu bisa terbang?",
  "Jika kamu bisa menghapus satu dosa di dunia, dosa apa yang kamu pilih?",
  "Jika kamu mendapat uang 100 juta dalam semalam, apa yang ingin kamu lakukan?",
  "Bagaimana jika kamu mempergoki pacarmu selingkuh dengan sahabat dekatmu?",
  "Jika kamu kebal terhadap satu penyakit, penyakit apa yang kamu pilih?",
  "Jika kamu dilahirkan kembali sebagai bukan manusia, kamu mau jadi apa?",
  "Jika kamu bisa mengambil alih satu perusahaan, perusahaan apa yang kamu pilih?",
  "Jika kamu bisa masuk ke dunia kartun, kartun apa yang kamu pilih dan kenapa?",
  "Jika kamu bisa memainkan alat musik, alat apa yang kamu pilih?",
  "Jika diberi satu permintaan, kamu ingin meminta apa?",
  "Jika kamu hebat dalam satu olahraga, olahraga apa yang kamu pilih?",
  "Jika kamu hanya bisa makan satu jenis makanan seumur hidup, apa yang kamu pilih?",
  "Jika diberi liburan gratis ke mana pun, kamu mau ke mana?",
  "Jika kamu bisa punya kekuatan superhero, apa dan kenapa?",
  "Jika kamu bisa mengendalikan satu elemen, elemen apa yang kamu pilih?",
  "Jika kamu bisa tinggal di mana saja di dunia, di mana kamu ingin tinggal?",
  "Jika kamu bisa memelihara hewan buas, hewan apa yang kamu pilih?",
  "Jika kamu bisa kembali ke masa lalu dan ubah satu keputusan, apa yang kamu ubah?",
  "Jika kamu bisa memilih artis untuk jadi pasangan, siapa yang kamu pilih?",
  "Jika kamu bisa belajar satu skill dalam semalam, skill apa itu?",
  "Jika kamu bisa membelah diri, apa yang akan kamu lakukan?",
  "Jika kamu bisa ngobrol dengan dirimu usia 10 tahun, apa nasihatmu?",
  "Jika kamu berada di situasi perang, peran apa yang kamu pilih?",
  "Jika kamu bisa bicara dengan tokoh sejarah, siapa dan apa yang akan kamu tanya?",
  "Jika kamu bisa wujudkan rumah impian, rumah seperti apa yang kamu mau?",
  "Jika kamu bisa hidup di era sejarah manapun, era apa dan kenapa?",
  "Jika kamu bisa hapus satu kejahatan di dunia, kejahatan apa yang kamu hapus?",
  "Jika kamu diberi anugerah untuk membuktikan satu kebenaran, teori apa itu?",
  "Jika kamu punya 24 jam di dunia sendirian, apa yang akan kamu lakukan?",
  "Jika kamu bisa berbicara semua bahasa di dunia, kamu akan pakai untuk apa?",
  "Jika kamu bisa bertemu dirimu di masa depan, kamu ingin tahu apa?",
  "Jika kamu bangun sebagai orang lain, siapa yang ingin kamu alami hidupnya?",
  "Jika kamu bisa hidup tanpa rasa takut, apa yang akan kamu lakukan pertama kali?",
  "Jika semua orang jujur padamu selama 1 hari, siapa yang akan kamu tanya duluan?",
  "Jika kamu bisa menghapus satu kenangan, kenangan apa yang kamu hapus?",
  "Jika kamu bisa mengulang satu hari dalam hidupmu, hari apa itu dan kenapa?",
  "Jika kamu hanya punya satu minggu untuk hidup, apa yang akan kamu lakukan?",
  "Jika kamu bisa memecahkan satu misteri dunia, misteri apa yang kamu pilih?",
  "Jika kamu tidak bisa berkata-kata seumur hidup, bagaimana kamu akan berkomunikasi?",
  "Jika kamu harus memilih satu hal untuk diwariskan ke dunia, apa itu?",
  "Jika kamu bisa melihat masa depan, apa yang ingin kamu lihat?",
  "Jika kamu bisa menulis surat untuk Tuhan, apa yang akan kamu tulis?",
  "Jika kamu punya kesempatan untuk memulai ulang hidup, apakah kamu akan ambil?",
  "Jika kamu bisa membuat satu perubahan besar di negaramu, perubahan apa itu?",
  "Jika kamu harus hidup sendiri di pulau terpencil, benda apa yang akan kamu bawa?",
  "Jika kamu bisa menjadi terkenal untuk satu hal, kamu ingin dikenal karena apa?",
  "Jika kamu bisa menghidupkan kembali satu orang dari masa lalu, siapa dan kenapa?",
];

// =================== TOP 3 ===================
export const top3Questions = [
  "Makanan favorit kamu!",
  "Minuman favorit kamu!",
  "Tempat makan favorit kamu!",
  "Makanan tradisional yang kamu suka!",
  "Jajanan minimarket favorit!",
  "Minuman dingin favorit!",
  "Camilan asin favorit!",
  "Camilan manis favorit!",
  "Menu restoran cepat saji favorit!",
  "Menu cafe favorit!",
  "Jajanan masa kecil favorit!",
  "Makanan yang bikin nostalgia!",
  "Game yang paling kamu suka!",
  "Film Indonesia favorit!",
  "Film Barat favorit!",
  "Serial TV favorit!",
  "Kartun atau animasi favorit!",
  "Karakter kartun favorit!",
  "Content creator favorit!",
  "Komedian favorit!",
  "Lagu Indonesia favorit!",
  "Lagu Barat favorit!",
  "Penyanyi solo Indonesia favorit!",
  "Penyanyi solo luar negeri favorit!",
  "Band Indonesia favorit!",
  "Band luar negeri favorit!",
  "Warna favorit kamu!",
  "Benda yang selalu kamu bawa!",
  "Tempat nongkrong favorit!",
  "Aplikasi yang paling sering kamu buka!",
  "Negara yang pengen kamu kunjungi!",
  "Destinasi liburan impian!",
  "Kenangan terbaik masa kecil!",
  "Mainan masa kecil favorit!",
  "Acara TV favorit waktu kecil!",
  "Pelajaran favorit waktu sekolah!",
  "Guru yang paling berkesan!",
  "Mata pelajaran yang kamu kuasai!",
  "Pekerjaan impian kamu!",
  "Hal yang bikin kamu bahagia!",
  "Barang yang paling kamu sayang!",
  "Tempat yang bikin kamu tenang!",
  "Kebiasaan unik kamu!",
  "Skill yang pengen kamu pelajari!",
  "Hal yang pengen kamu capai tahun ini!",
  "Momen paling lucu dalam hidupmu!",
  "Quotes yang kamu suka!",
  "Hewan peliharaan impian!",
  "Olahraga favorit!",
  "Hobi kamu saat ini!",
];

export const dttQuestions = [
  "Apa hal tergila yang pengen banget kita lakuin bareng?",
  "Menurut kamu, kita berdua itu vibes-nya kayak karakter siapa sih?",
  "Pernah gak ngerasa kita sempat jauh? Kenapa ya waktu itu?",
  "Kalau aku tiba-tiba ngilang seminggu, kamu bakal ngapain?",
  "Apa momen barengku yang paling kamu ingat sampai sekarang?",
  "Pernah gak kamu pura-pura fine di depanku padahal lagi hancur banget?",
  "Hal apa yang kamu syukuri dari persahabatan kita?",
  "Menurutmu, tapa yang bikin kita cocok banget jadi sahabat?",
  "Kalau kita bikin janji 10 tahun lagi mau ngapain, kamu mau ngapain bareng aku?",
  "Pernah gak kamu ngerasa aku berubah? Ke arah lebih baik atau buruk?",
  "Apa hal paling konyol yang pernah kita lakuin bareng?",
  "Kalau aku punya pacar yang gak kamu suka, kamu bakal jujur gak?",
  "Hal apa yang paling bikin kamu nyaman curhat ke aku?",
  "Kita lebih sering ngakak atau saling nenangin, ya?",
  "Apa satu hal yang kamu pengen aku tahu tapi kamu belum pernah ngomong?",
  "Menurutmu, aku tipe orang yang gampang disayang atau susah didekati?",
  "Pernah gak kamu ngerasa disakitin sama aku? Tapi gak kamu bilangin?",
  "Kalau hidup kamu difilmkan, aku jadi karakter apa?",
  "Apa kebiasaan aku yang paling ngeselin tapi kamu udah pasrah aja?",
  "Apa versi terbaik dari aku yang pernah kamu lihat?",
  "Kalau kita lost contact selama 3 tahun, kira-kira apa yang bikin kita reconnect?",
  "Menurutmu, aku orang yang jujur sepenuhnya atau suka nyimpen sendiri?",
  "Hal apa yang kamu harap nggak pernah berubah dari aku?",
  "Kalau kamu lagi sedih, hal apa yang kamu harap aku lakuin?",
  "Pernah gak kamu ngerasa bersaing diam-diam sama aku?",
  "Kalau kita tukeran hidup selama sehari, apa yang bakal kamu lakuin?",
  "Apa hal paling random yang bikin kamu inget aku?",
  "Kalau kamu bisa bantu aku sembuhin satu luka batin, itu soal apa?",
  "Menurutmu, aku bisa diandalkan gak pas kamu bener-bener butuh?",
  "Pernah gak kamu nutupin sesuatu dariku demi gak nyakitin aku?",
  "Kalau kita gak ketemu di kehidupan ini, hidupmu bakal beda di bagian mana?",
  "Menurut kamu, persahabatan kita lebih ke support system, chaos partner, atau combo?",
  "Hal apa dari aku yang paling kamu khawatirkan, tapi kamu simpan sendiri?",
  "Kalau kita berantem parah, siapa yang kemungkinan besar bakal minta maaf duluan?",
  "Apa kata yang paling menggambarkan persahabatan kita?",
  "Apa hal paling tulus yang pernah aku lakuin buat kamu?",
  "Menurutmu, kita masih bakal deket gak kalau udah punya keluarga masing-masing?",
  "Kalau aku lagi down banget tapi diem-diem aja, kamu bakal tahu dari mana?",
  "Pernah gak kamu ngelindungin aku tanpa aku tahu?",
  "Kalau kita punya tradisi tahunan, kamu pengen itu tentang apa?",
];
