export const totQuestions = [
  "Liburan ke Pantai atau Gunung?",
  "Penampilan baik atau sifat baik?",
  "Tenar atau Pintar?",
  "Goodlooking miskin atau jelek kaya?",
  "Mie goreng atau Mie Kuah?",
  "Kegiatan indoor atau outdoor?",
  "Bisa ngilang atau bisa terbang?",
  "Nasi goreng atau nasi uduk?",
  "Lagu barat atau lagu indo?",
  "Indomaret atau Alfamart?",
  "Film atau series?",
  "Jago olahraga atau jago musik?",
  "Cash atau cashless?",
  "Lagu galau atau lagu semangat?",
  "Kucing atau anjing?",
  "TikTok atau Instagram?",
  "KFC atau McD?",
  "Banyak uang sedikit waktu atau pas-pasan banyak waktu?",
  "Coca-Cola atau Sprite?",
  "Kopi atau non kopi?",
  "Coklat atau keju?",
  "Good looking tapi telmi atau biasa aja tapi pintar?",
  "Film action atau drama?",
  "Goodlooking tapi bau atau wangi tapi jelek?",
  "Pasangan introvert atau extrovert?",
  "Bau mulut atau bau badan?",
  "Liburan bareng keluarga atau teman?",
  "Kecap atau sambel?",
  "Jogging pagi atau sore?",
];

export const dtpQuestions = [
  "Apa yang pertama kali bikin kamu tertarik padaku?",
  "Bagaimana kamu tahu bahwa kamu jatuh cinta padaku?",
  "Apa ketakutan terbesarmu dalam hubungan ini?",
  "Hal apa dalam diriku yang paling kamu syukuri?",
  "Apa yang menurutmu paling sulit dalam menjaga hubungan?",
  "Bagaimana kamu ingin kita menyelesaikan konflik di masa depan?",
  "Pernahkah kamu merasa tidak cukup baik dalam hubungan ini?",
  "Bagaimana cara terbaik aku menunjukkan cinta kepadamu?",
  "Apa harapanmu untuk hubungan kita lima tahun ke depan?",
  "Bagian mana dari masa lalumu yang masih membentuk dirimu saat ini?",
  "Bagaimana kamu mendefinisikan komitmen dalam hubungan?",
  "Apa yang kamu takutkan jika kita terlalu dekat?",
  "Apa yang membuatmu merasa benar-benar aman dalam hubungan ini?",
  "Apa momen paling berarti yang pernah kita lewati bersama?",
  "Bagaimana caramu memproses rasa cemburu dalam hubungan?",
  "Apa yang membuatmu merasa didengar dan dimengerti olehku?",
  "Hal apa yang kamu takutkan aku tidak akan mengerti tentangmu?",
  "Apa satu hal yang belum pernah kamu ceritakan padaku, tapi ingin kamu bagi suatu hari nanti?",
  "Apa yang kamu harapkan bisa lebih sering kita lakukan bersama?",
  "Apa arti 'rumah' dalam konteks hubungan bagi kamu?",
  "Apa kekhawatiranmu tentang masa depan kita?",
  "Apa bentuk kasih sayang yang paling membuatmu merasa dicintai?",
  "Kapan kamu merasa paling rentan dalam hubungan ini?",
  "Jika kita sedang menghadapi masa sulit, apa yang kamu ingin aku lakukan?",
  "Apa yang paling kamu butuhkan dariku saat kamu merasa sedih?",
  "Apakah kamu merasa kita sudah jujur sepenuhnya satu sama lain?",
  "Apa yang menurutmu bisa kita perbaiki dalam cara kita berkomunikasi?",
  "Apa yang kamu pelajari tentang cinta dari hubungan kita?",
  "Apa satu hal tentang diriku yang kamu takut akan berubah seiring waktu?",
  "Apa impian terbesar kamu yang ingin aku dukung sepenuhnya?",
  "Apa rasa sakit terbesar yang masih kamu bawa, dan bagaimana aku bisa membantumu pulih?",
  "Apakah ada bagian dari dirimu yang belum bisa kamu tunjukkan ke aku sepenuhnya? Kenapa?",
  "Kapan terakhir kamu merasa benar-benar terhubung denganku?",
  "Apa artinya setia menurutmu?",
  "Apakah kamu merasa dicintai apa adanya olehku?",
  "Bagaimana kamu membayangkan hubungan ideal kita ke depannya?",
  "Apa ketakutan terbesar kamu jika hubungan ini gagal?",
  "Apa satu hal yang selalu ingin kamu lakukan bersamaku tapi belum sempat?",
  "Apa peran pasangan dalam proses penyembuhan luka masa lalu menurutmu?",
  "Apa momen kecil dariku yang diam-diam kamu ingat sampai sekarang?",
  "Bagaimana aku bisa menjadi pasangan yang lebih baik bagimu?",
  "Apa hal paling menyakitkan yang pernah kamu alami dalam hubungan sebelum ini?",
  "Apa yang menurutmu paling bisa menghancurkan kepercayaan dalam hubungan?",
  "Apa yang membuatmu yakin bahwa aku adalah orang yang tepat untukmu?",
  "Apakah kamu merasa bebas menjadi diri sendiri saat bersamaku?",
  "Bagaimana cara kamu mengekspresikan cinta ketika kata-kata tidak cukup?",
  "Apa perasaan yang paling sulit kamu ungkapkan kepadaku?",
  "Apa yang membuatmu merasa dihargai dalam hubungan ini?",
  "Apakah kamu pernah merasa sendirian walaupun kita sedang bersama?",
  "Bagaimana kamu ingin aku mencintaimu saat kamu sedang tidak baik-baik saja?",
];

export const whatIfQuestions = [
  "Apa yang akan kamu lakukan jika kamu bisa menghentikan waktu?",
  "Bagaimana jika kamu bisa membaca pikiran orang lain?",
  "Kalau kamu jadi presiden sehari, apa yang kamu lakukan?",
  "Bagaimana jika kamu bisa terbang?",
  "Jika kamu bisa menghapus satu dosa di dunia, dosa apa yang kamu pilih?",
  "Jika kamu mendapat uang 100 juta dalam semalam, apa yang ingin kamu lakukan?",
  "Bagaimana jika kamu mempergoki pacarmu selingkuh dengan sahabat dekatmu?",
  "Jika kamu kebal terhadap satu penyakit, penyakit apa yang kamu pilih?",
  "Jika kamu dilahirkan kembali sebagai bukan manusia, kamu mau jadi apa?",
  "Jika kamu bisa mengambil alih satu perusahaan, perusahaan apa yang kamu pilih?",
  "Jika kamu bisa masuk ke dunia kartun, kartun apa yang kamu pilih dan kenapa?",
  "Jika kamu bisa memainkan alat musik, alat apa yang kamu pilih?",
  "Jika diberi satu permintaan, kamu ingin meminta apa?",
  "Jika kamu hebat dalam satu olahraga, olahraga apa yang kamu pilih?",
  "Jika kamu hanya bisa makan satu jenis makanan seumur hidup, apa yang kamu pilih?",
  "Jika diberi liburan gratis ke mana pun, kamu mau ke mana?",
  "Jika kamu bisa punya kekuatan superhero, apa dan kenapa?",
  "Jika kamu bisa mengendalikan satu elemen, elemen apa yang kamu pilih?",
  "Jika kamu bisa tinggal di mana saja di dunia, di mana kamu ingin tinggal?",
  "Jika kamu bisa memelihara hewan buas, hewan apa yang kamu pilih?",
  "Jika kamu bisa kembali ke masa lalu dan ubah satu keputusan, apa yang kamu ubah?",
  "Jika kamu bisa memilih artis untuk jadi pasangan, siapa yang kamu pilih?",
  "Jika kamu bisa belajar satu skill dalam semalam, skill apa itu?",
  "Jika kamu bisa membelah diri, apa yang akan kamu lakukan?",
  "Jika kamu bisa ngobrol dengan dirimu usia 10 tahun, apa nasihatmu?",
  "Jika kamu berada di situasi perang, peran apa yang kamu pilih?",
  "Jika kamu bisa bicara dengan tokoh sejarah, siapa dan apa yang akan kamu tanya?",
  "Jika kamu bisa wujudkan rumah impian, rumah seperti apa yang kamu mau?",
  "Jika kamu bisa hidup di era sejarah manapun, era apa dan kenapa?",
  "Jika kamu bisa hapus satu kejahatan di dunia, kejahatan apa yang kamu hapus?",
  "Jika kamu diberi anugerah untuk membuktikan satu kebenaran, teori apa itu?",
  "Jika kamu punya 24 jam di dunia sendirian, apa yang akan kamu lakukan?",
];

// =================== TOP 3 ===================
export const top3Questions = [
  "Makanan favoritmu!",
  "Makanan tradisional yang paling kamu suka!",
  "Streetfood favoritmu!",
  "Minuman minimarket favorit!",
  "Makanan minimarket favoritmu!",
  "Menu cafe favoritmu!",
  "Cafe di daerahmu!",
  "Film Indonesia favoritmu!",
  "Film Barat favoritmu!",
  "Series favoritmu!",
  "Kartun/animasi favoritmu!",
  "Game favoritmu!",
  "Penyanyi solo Indonesia favoritmu!",
  "Band Indonesia favoritmu!",
  "Penyanyi Barat favoritmu!",
  "Band Barat favoritmu!",
  "Lagu Indonesia favoritmu!",
  "Lagu Barat favoritmu!",
  "Content creator favoritmu!",
  "Komedian favoritmu!",
  "Warna favoritmu!",
  "Mainan masa kecil favoritmu!",
  "Jajanan masa kecil favoritmu!",
  "Pekerjaan idamanmu!",
  "Brand fashion favoritmu!",
  "Olahraga favoritmu!",
  "Destinasi liburan impianmu!",
  "Mata pelajaran favoritmu!",
  "Negara yang paling ingin kamu kunjungi!",
  "Acara televisi favoritmu!",
];

export const dttQuestions = [
  "Apa hal tergila yang pengen banget kita lakuin bareng?",
  "Menurut kamu, kita berdua itu vibes-nya kayak karakter siapa sih?",
  "Pernah gak ngerasa kita sempat jauh? Kenapa ya waktu itu?",
  "Kalau aku tiba-tiba ngilang seminggu, kamu bakal ngapain?",
  "Apa momen barengku yang paling kamu ingat sampai sekarang?",
  "Pernah gak kamu pura-pura fine di depanku padahal lagi hancur banget?",
  "Hal apa yang kamu syukuri dari persahabatan kita?",
  "Menurutmu, tapa yang bikin kita cocok banget jadi sahabat?",
  "Kalau kita bikin janji 10 tahun lagi mau ngapain, kamu mau ngapain bareng aku?",
  "Pernah gak kamu ngerasa aku berubah? Ke arah lebih baik atau buruk?",
  "Apa hal paling konyol yang pernah kita lakuin bareng?",
  "Kalau aku punya pacar yang gak kamu suka, kamu bakal jujur gak?",
  "Hal apa yang paling bikin kamu nyaman curhat ke aku?",
  "Kita lebih sering ngakak atau saling nenangin, ya?",
  "Apa satu hal yang kamu pengen aku tahu tapi kamu belum pernah ngomong?",
  "Menurutmu, aku tipe orang yang gampang disayang atau susah didekati?",
  "Pernah gak kamu ngerasa disakitin sama aku? Tapi gak kamu bilangin?",
  "Kalau hidup kamu difilmkan, aku jadi karakter apa?",
  "Apa kebiasaan aku yang paling ngeselin tapi kamu udah pasrah aja?",
  "Apa versi terbaik dari aku yang pernah kamu lihat?",
  "Kalau kita lost contact selama 3 tahun, kira-kira apa yang bikin kita reconnect?",
  "Menurutmu, aku orang yang jujur sepenuhnya atau suka nyimpen sendiri?",
  "Hal apa yang kamu harap nggak pernah berubah dari aku?",
  "Kalau kamu lagi sedih, hal apa yang kamu harap aku lakuin?",
  "Pernah gak kamu ngerasa bersaing diam-diam sama aku?",
  "Kalau kita tukeran hidup selama sehari, apa yang bakal kamu lakuin?",
  "Apa hal paling random yang bikin kamu inget aku?",
  "Kalau kamu bisa bantu aku sembuhin satu luka batin, itu soal apa?",
  "Menurutmu, aku bisa diandalkan gak pas kamu bener-bener butuh?",
  "Pernah gak kamu nutupin sesuatu dariku demi gak nyakitin aku?",
  "Kalau kita gak ketemu di kehidupan ini, hidupmu bakal beda di bagian mana?",
  "Menurut kamu, persahabatan kita lebih ke support system, chaos partner, atau combo?",
  "Hal apa dari aku yang paling kamu khawatirkan, tapi kamu simpan sendiri?",
  "Kalau kita berantem parah, siapa yang kemungkinan besar bakal minta maaf duluan?",
  "Apa kata yang paling menggambarkan persahabatan kita?",
  "Apa hal paling tulus yang pernah aku lakuin buat kamu?",
  "Menurutmu, kita masih bakal deket gak kalau udah punya keluarga masing-masing?",
  "Kalau aku lagi down banget tapi diem-diem aja, kamu bakal tahu dari mana?",
  "Pernah gak kamu ngelindungin aku tanpa aku tahu?",
  "Kalau kita punya tradisi tahunan, kamu pengen itu tentang apa?",
];
